config/routes.rb
Rails.application.routes.draw do

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/edit_list", to: "user_movies#edit"
  patch "/edit_list", to: "user_movies#update" 
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :user_movies, only: [:create, :edit, :update, :destroy] 

  resources :movies

  resources :reviews

  resources :users do 
    resources :movies do 
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    end
  end


  root "static#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

    has_many :reviews
    has_many :reviewers, through: :reviews, source: :user
    has_many :user_movies 
    has_many :users, through: :user_movies

    accepts_nested_attributes_for :user_movies



    def rating_avg
        if self.reviews.size > 0
        ratings = self.reviews.map {|r| r.rating }
        ratings.sum / ratings.size
        else   
            0
        end
    end

    def self.sorted_by_rating
        self.all.sort_by{|movie| movie.rating_avg}.reverse
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user 
    belongs_to :movie
    validates_presence_of :rating 

end

app/models/static.rb
class Static < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
 
    has_many :reviews
    has_many :user_movies
    has_many :movies, through: :user_movies
    has_many :reviewed_movies, through: :reviews, source: :movie

    has_secure_password
    validates_presence_of :name, :username
    validates_uniqueness_of :username

    def self.create_by_github(auth_hash)
        self.find_or_create_by(username: auth_hash[:info][:nickname]) do |u|
          u.password = SecureRandom.hex
        end
    end

end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
    belongs_to :user
    belongs_to :movie

    scope :has_watched, -> {where(watched: true) } 

    def user_movie_title
        Movie.find_by(id: self.movie_id).title
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :verify_user

    private

    def verify_user
        redirect_to root_path unless logged_in?
    end
    
    def current_user 
        current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


    def index
        
    end

    def new 
        @movie = Movie.new
        @movie.user_movies.build
        @id = session[:user_id]
        flash[:notice] = "no reviews"
    end

    def create 
        if !Movie.find_by(title: movie_params[:title])
            movie = current_user.movies.build(movie_params)
            if movie.save 
                redirect_to movie_path(movie)
            else 
                render "new"
            end
        else  
            movie = Movie.find_by(title: movie_params[:title])
            redirect_to movie_path(movie), alert: "movie already exists, add below"
        end
    end

    def show
        @movie = Movie.find(params[:id])
        @user = current_user
        @new_user_movie = @movie.user_movies.build
        @user_movie = current_user.user_movies.find_by(movie_id: params[:id])
        # byebug
        # redirect_to "/"
    end

    private 

    def movie_params 
        params.require(:movie).permit(:title, user_movies_attributes: [:watched, :user_id] )
    end
    

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new 
        @review = Review.new
        @movie = Movie.find(params[:movie_id])
        @user = current_user
    end

    def create
        @review = Review.new(review_params)
        if @review.save
            redirect_to movie_path(@review.movie)
        end
    end

    def edit
            @review = Review.find(params[:id])
            @movie = Movie.find(params[:movie_id])
            @user = User.find(params[:user_id])
            if current_user.id != @user.id
                flash[:unauthorized] = "You can only edit your own reviews"
                redirect_to movie_path(@movie)
            end
    end

    def update 
        @review = Review.find(params[:id])
        @review.update(review_params)
        redirect_to movie_path(@review.movie)
    end

    private 

    def review_params
        params.require(:review).permit(:rating, :content, :movie_id, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :create
    skip_before_action :verify_user, only: [:new, :create]
    # skip_before_action :verify_authenticity_token, only: :create



    def new
         @user = User.new
    end

    def create 
        if auth_hash
            @user = User.create_by_github(auth_hash)
            @user.name = auth_hash[:info][:name]
            @user.save
            session[:user_id] = @user.id
        else 
            @user = User.find_by(username: params[:username])
            authenticated = @user.try(:authenticate, params[:password])
            return head(:forbidden) unless authenticated
            # @user = user
            session[:user_id] = @user.id
        end
        redirect_to @user
    end

    def destroy 
        session.delete :user_id
        redirect_to "/"
    end

    protected   

    def auth_hash
        request.env['omniauth.auth']
    end
    

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    skip_before_action :verify_user
    skip_before_action :verify_authenticity_token

    def home
         redirect_to user_path(current_user) if logged_in?
        
    end
end

app/controllers/user_movies_controller.rb
class UserMoviesController < ApplicationController

    def create
        @user_movie = UserMovie.new(user_movie_params)
        @user_movie.save 
        redirect_to "/"
    end

    def edit
        @user_movie = current_user.user_movies.find_by(movie_id: params[:id])
        @user_movies = current_user.user_movies
    end

    def update
        @user_movie = current_user.user_movies.find_by(movie_id: params[:user_movie][:movie_id])
        @user_movie.update(user_movie_params)
        redirect_to user_path(current_user)
    end

    def destroy 
        UserMovie.find(params[:id]).destroy
        redirect_to "/edit_list"
    end

    private 

    def user_movie_params
        params.require(:user_movie).permit(:movie_id, :user_id, :watched)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_user, only: [:new, :create]

    def new
        redirect_to user_path(current_user) if logged_in?
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            flash[:alert] = @user.errors.full_messages.join( ", ")
            redirect_to signup_path
        end
    end

    def show 
        @user = User.find_by(id: params[:id])
        redirect_to "/" if @user.id != current_user.id
    end

    private 
    
    def user_params 
        params.require(:user).permit(:name, :username, :password)
    end

    # def require_login
    #     return head(:forbidden) unless session[:user_id] == current_user.id
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user 
        current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/helpers/movie_reviews_helper.rb
module MovieReviewsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/index.html.erb
<h3>Select a Movie Below</h3>
    <% Movie.sorted_by_rating.each do |movie|  %>
    <ul>
        <li> 
            <strong><%= link_to movie.title, movie_path(movie) %></strong>
            <% if movie.rating_avg > 0%> 
            <%= "#{movie.rating_avg}%" %>
            <% else %>
            <%= flash[:notice]%>
            <% end %><br>
            <% movie.reviews.each do |review| %>
                <strong><%= review.user.username %></strong>
                <%= "#{review.rating}%" %> <br>
                <%= review.content %>
            <% end %> 
        </li>
    </ul>
    <% end %>

app/views/movies/new.html.erb
<h3>Add a Movie to the list</h3>
<%= form_for @movie do |f| %>
   
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.fields_for :user_movies do |form| %>
        <%= form.hidden_field :user_id, value: @id %>
        <%= form.label "check if already seen", :watched %>
        <%= form.check_box :watched %>
    <% end %>
    <%= f.submit %>
<% end %>
    


    

app/views/movies/show.html.erb
<%= flash[:alert] %>
<h2><%= flash[:unauthorized] %></h2>

<h1><%= @movie.title %></h1>
<h2>Potatometer: <%= @movie.rating_avg %>%</h2>
<% @movie.reviews.each do |review| %>
    <div>
        <strong><%= review.user.username %>:</strong>
        <%= review.rating %>%<br>
        <%= review.content %><br>
        <% if review.user_id == @user.id%>
            <%= link_to "Edit Review", edit_user_movie_review_path(@user, @movie, review) %>
        <% end %> 
    </div><br>
<% end %> 

<% if @user.user_movies.find_by(movie_id: @movie.id) %>
    <%= form_with model: @user_movie, url: edit_list_path, method: :patch do |f| %>
        <%= render :partial => "/user_movies/form", :locals => {f: f}%>
        <%= f.submit "Update" %>
    <% end %>
<% else %>
    <%= form_for @new_user_movie do |f| %>
        <%= render :partial => "/user_movies/form", :locals => {f: f}%>
        <%= f.submit "add movie to list" %>
    <% end %>
<% end %>


<%= link_to "add another movie", new_user_movie_path(@user) %> <br>



<% if  @user_movie && @user_movie.watched && !@user.reviews.find_by(movie_id: @user_movie.movie_id) %>
    <%= link_to "leave a review", new_user_movie_review_path(@user, @movie) %>
<% end %>

app/views/reviews/_form.html.erb
<h2><%= @movie.title %></h2><br>
<%= form_for @review do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :movie_id, value: @movie.id %>
    <%= f.label :rating, "Percent:" %>
    <%= f.number_field :rating, min: 1, max: 100 %> <br>
    <%= f.label :content, "Use Your Words" %> <br>
    <%= f.text_area :content, :size => "60%x5%" %> <br>
    <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<%= render "form" %>

app/views/reviews/new.html.erb
<%= form_for @review do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :movie_id, value: @movie.id %>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "Create User" %>
<% end %>

app/views/users/new.html.erb
<%= render "form" %>

<%= flash[:alert] %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h2>Your Movie List</h2>
<% @user.movies.sorted_by_rating.each do |movie| %>
    <ul>
        <li><%= link_to movie.title, movie_path(movie)%> 
        <% if @user.user_movies.has_watched.find_by(movie_id: movie.id) %>
        &#9989;
        <% end %> </li>
    </ul>
<% end%>

<%= link_to "Edit Your Watchlist", edit_list_path %> <br>
<%= link_to "Add Movies to your watchlist", new_user_movie_path(@user)%> <br>